const resObj = [
  {
    id: "334475",
    name: "Domino",
    costForTwo: 40000,
    avgRating: "3.5",
    cusine: "Pizza Asian taste",
  },
  {
    id: "334476",
    name: "KFC",
    costForTwo: 50000,
    avgRating: "4.8",
    cusine: "Broast Asian taste",
  },
  {
    id: "334477",
    name: "Monty",
    costForTwo: 60000,
    avgRating: "3.8",
    cusine: "Shwarma Asian taste",
  },
  {
    id: "334478",
    name: "Coconut Groove",
    costForTwo: 90000,
    avgRating: "5.0",
    cusine: "Burgers",
  },
  {
    id: "334479",
    name: "Majesty pasta",
    costForTwo: 20000,
    avgRating: "3.0",
    cusine: "Pasta Asian taste",
  },
  {
    id: "334480",
    name: "Shakes",
    costForTwo: 40000,
    avgRating: "4.8",
    cusine: "Biryani Asian taste",
  },
  {
    id: "334481",
    name: "Qorma",
    costForTwo: 40000,
    avgRating: "4.8",
    cusine: "Biryani Asian taste",
  },
  {
    id: "334482",
    name: "Biryani",
    costForTwo: 40000,
    avgRating: "4.8",
    cusine: "Biryani Asian taste",
  },
  {
    id: "334483",
    name: "Pie",
    costForTwo: 40000,
    avgRating: "4.8",
    cusine: "Biryani Asian taste",
  },
  {
    id: "334484",
    name: "Ice cream",
    costForTwo: 40000,
    avgRating: "4.8",
    cusine: "Biryani Asian taste",
  },
  {
    id: "334485",
    name: "Alfredo pasta",
    costForTwo: 40000,
    avgRating: "4.8",
    cusine: "Biryani Asian taste",
  },
];

export default resObj;
